name: Linux

on:
  workflow_call:

jobs:
  docs_link_spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/ci/docs_check.sh

  test_on_alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine
      # Docker restricts io_uring by default, running unconfined then.
      options: --security-opt seccomp=unconfined
    steps:
      - run: apk add -U git
      # https://github.com/actions/checkout/issues/1169
      - run: git config --system --add safe.directory '*'
      - uses: actions/checkout@v4
        # Fetch the entire history of the commit in question for tidy.
        with:
          fetch-depth: 2147483647
      - run: ./scripts/install_zig.sh
      - run: zig/zig build test

  test_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2147483647
      - run: ./scripts/install_zig.sh
      - run: zig/zig build test
      - run: zig/zig build -Dtracer-backend=tracy

  aof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: ./.github/ci/test_aof.sh

  c_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build clients:c:sample -Drelease

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build fuzz -- smoke

  # Run simulator once for each state machine, using commit hash as a random, but also deterministic
  # seed.
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh
      - run: zig/zig build vopr -Dsimulator-state-machine=accounting -Drelease -- ${{ github.sha }}
      - run: zig/zig build vopr -Dsimulator-state-machine=testing    -Drelease -- ${{ github.sha }}
